import { Gender, MaritalStatus, WorkStatus, RequestStatus } from '@prisma/client'

export const maritalStatus = [
  { [MaritalStatus.SINGLE]: 'single' },
  { [MaritalStatus.MARRIED]: 'married' },
  { [MaritalStatus.DIVORCED]: 'divorced' },
  { [MaritalStatus.WIDOWED]: 'widowed' },
  { [MaritalStatus.COHABITING]: 'cohabiting' },
]

export const maritalOptions: {
  [key in MaritalStatus]: string
} = Object.assign({}, ...maritalStatus)

export const workStatusOptions = {
  [WorkStatus.EMPLOYEE]: 'employee',
  [WorkStatus.ENTREPRENEUR]: 'entrepreneur',
  [WorkStatus.UNEMPLOYED]: 'unemployed',
  [WorkStatus.STUDENT]: 'student',
  [WorkStatus.RETIRED]: 'retired',
  [WorkStatus.OTHER]: 'other',
}

export const genderOptions = {
  [Gender.MALE]: 'male',
  [Gender.FEMALE]: 'female',
}

export const genderTypes = {
  [Gender.MALE]: 'male_type',
  [Gender.FEMALE]: 'female_type',
}

export const profileStatus = {
  [RequestStatus.PENDING]: 'pending',
  [RequestStatus.APPROVED]: 'approved',
  [RequestStatus.REJECTED]: 'rejected',
  [RequestStatus.INCOMPLETE]: 'incomplete',
}

type TranslationFunction = (key: string) => string

export function getTranslatedOptions<T extends Record<string, string>>(
  options: T,
  translate: TranslationFunction,
  prefix: string,
): { [K in keyof T]: string } {
  return Object.fromEntries(
    Object.entries(options).map(
      ([key, value]) => [key, translate(`${prefix}.${value}`)],
    ),
  ) as { [K in keyof T]: string }
}

export const countryKeys = [
  'afghanistan',
  'south_africa',
  'albania',
  'algeria',
  'germany',
  'andorra',
  'angola',
  'antigua_and_barbuda',
  'saudi_arabia',
  'argentina',
  'armenia',
  'australia',
  'austria',
  'azerbaijan',
  'bahamas',
  'bahrain',
  'bangladesh',
  'barbados',
  'belgium',
  'belize',
  'benin',
  'bhutan',
  'belarus',
  'myanmar',
  'bolivia',
  'bosnia_and_herzegovina',
  'botswana',
  'brazil',
  'brunei',
  'bulgaria',
  'burkina_faso',
  'burundi',
  'cambodia',
  'cameroon',
  'canada',
  'cape_verde',
  'central_african_republic',
  'chile',
  'china',
  'cyprus',
  'colombia',
  'comoros',
  'republic_of_congo',
  'democratic_republic_of_congo',
  'north_korea',
  'south_korea',
  'costa_rica',
  'ivory_coast',
  'croatia',
  'cuba',
  'denmark',
  'djibouti',
  'dominica',
  'egypt',
  'united_arab_emirates',
  'ecuador',
  'eritrea',
  'spain',
  'estonia',
  'united_states',
  'ethiopia',
  'fiji',
  'finland',
  'france',
  'gabon',
  'gambia',
  'georgia',
  'ghana',
  'greece',
  'grenada',
  'guatemala',
  'guinea',
  'guinea_bissau',
  'equatorial_guinea',
  'guyana',
  'haiti',
  'honduras',
  'hong_kong',
  'hungary',
  'marshall_islands',
  'solomon_islands',
  'india',
  'indonesia',
  'iran',
  'iraq',
  'ireland',
  'iceland',
  'israel',
  'italy',
  'jamaica',
  'japan',
  'jordan',
  'kazakhstan',
  'kenya',
  'kyrgyzstan',
  'kiribati',
  'kuwait',
  'laos',
  'lesotho',
  'latvia',
  'lebanon',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'macedonia',
  'madagascar',
  'malaysia',
  'malawi',
  'maldives',
  'mali',
  'malta',
  'morocco',
  'cook_islands',
  'mauritius',
  'mauritania',
  'mexico',
  'micronesia',
  'moldova',
  'monaco',
  'mongolia',
  'montenegro',
  'mozambique',
  'namibia',
  'nauru',
  'nepal',
  'nicaragua',
  'niger',
  'nigeria',
  'niue',
  'norway',
  'new_zealand',
  'oman',
  'uganda',
  'uzbekistan',
  'pakistan',
  'palau',
  'panama',
  'papua_new_guinea',
  'paraguay',
  'netherlands',
  'peru',
  'philippines',
  'poland',
  'portugal',
  'qatar',
  'dominican_republic',
  'czech_republic',
  'romania',
  'united_kingdom',
  'russia',
  'rwanda',
  'saint_kitts_and_nevis',
  'saint_lucia',
  'san_marino',
  'saint_vincent_and_grenadines',
  'el_salvador',
  'samoa',
  'sao_tome_and_principe',
  'senegal',
  'serbia',
  'seychelles',
  'sierra_leone',
  'singapore',
  'slovakia',
  'slovenia',
  'somalia',
  'sudan',
  'south_sudan',
  'sri_lanka',
  'sweden',
  'switzerland',
  'suriname',
  'swaziland',
  'syria',
  'tajikistan',
  'tanzania',
  'chad',
  'thailand',
  'east_timor',
  'togo',
  'tonga',
  'trinidad_and_tobago',
  'tunisia',
  'turkmenistan',
  'turkey',
  'tuvalu',
  'ukraine',
  'uruguay',
  'vanuatu',
  'vatican',
  'venezuela',
  'vietnam',
  'yemen',
  'zambia',
  'zimbabwe',
] as const

export type CountryKey = typeof countryKeys[number];

export const phoneCountries = [
  { value: '+213', label: 'algeria', flag: '🇩🇿' },
  { value: '+49', label: 'germany', flag: '🇩🇪' },
  { value: '+244', label: 'angola', flag: '🇦🇴' },
  { value: '+54', label: 'argentina', flag: '🇦🇷' },
  { value: '+374', label: 'armenia', flag: '🇦🇲' },
  { value: '+61', label: 'australia', flag: '🇦🇺' },
  { value: '+43', label: 'austria', flag: '🇦🇹' },
  { value: '+994', label: 'azerbaijan', flag: '🇦🇿' },
  { value: '+973', label: 'bahrain', flag: '🇧🇭' },
  { value: '+880', label: 'bangladesh', flag: '🇧🇩' },
  { value: '+32', label: 'belgium', flag: '🇧🇪' },
  { value: '+229', label: 'benin', flag: '🇧🇯' },
  { value: '+375', label: 'belarus', flag: '🇧🇾' },
  { value: '+591', label: 'bolivia', flag: '🇧🇴' },
  { value: '+387', label: 'bosnia_and_herzegovina', flag: '🇧🇦' },
  { value: '+55', label: 'brazil', flag: '🇧🇷' },
  { value: '+359', label: 'bulgaria', flag: '🇧🇬' },
  { value: '+226', label: 'burkina_faso', flag: '🇧🇫' },
  { value: '+257', label: 'burundi', flag: '🇧🇮' },
  { value: '+855', label: 'cambodia', flag: '🇰🇭' },
  { value: '+237', label: 'cameroon', flag: '🇨🇲' },
  { value: '+1', label: 'canada', flag: '🇨🇦' },
  { value: '+238', label: 'cape_verde', flag: '🇨🇻' },
  { value: '+56', label: 'chile', flag: '🇨🇱' },
  { value: '+86', label: 'china', flag: '🇨🇳' },
  { value: '+357', label: 'cyprus', flag: '🇨🇾' },
  { value: '+57', label: 'colombia', flag: '🇨🇴' },
  { value: '+242', label: 'republic_of_congo', flag: '🇨🇬' },
  { value: '+243', label: 'democratic_republic_of_congo', flag: '🇨🇩' },
  { value: '+506', label: 'costa_rica', flag: '🇨🇷' },
  { value: '+225', label: 'ivory_coast', flag: '🇨🇮' },
  { value: '+385', label: 'croatia', flag: '🇭🇷' },
  { value: '+53', label: 'cuba', flag: '🇨🇺' },
  { value: '+45', label: 'denmark', flag: '🇩🇰' },
  { value: '+253', label: 'djibouti', flag: '🇩🇯' },
  { value: '+20', label: 'egypt', flag: '🇪🇬' },
  { value: '+971', label: 'united_arab_emirates', flag: '🇦🇪' },
  { value: '+593', label: 'ecuador', flag: '🇪🇨' },
  { value: '+291', label: 'eritrea', flag: '🇪🇷' },
  { value: '+34', label: 'spain', flag: '🇪🇸' },
  { value: '+372', label: 'estonia', flag: '🇪🇪' },
  { value: '+1', label: 'united_states', flag: '🇺🇸' },
  { value: '+251', label: 'ethiopia', flag: '🇪🇹' },
  { value: '+679', label: 'fiji', flag: '🇫🇯' },
  { value: '+358', label: 'finland', flag: '🇫🇮' },
  { value: '+33', label: 'france', flag: '🇫🇷' },
  { value: '+241', label: 'gabon', flag: '🇬🇦' },
  { value: '+220', label: 'gambia', flag: '🇬🇲' },
  { value: '+995', label: 'georgia', flag: '🇬🇪' },
  { value: '+233', label: 'ghana', flag: '🇬🇭' },
  { value: '+30', label: 'greece', flag: '🇬🇷' },
  { value: '+502', label: 'guatemala', flag: '🇬🇹' },
  { value: '+224', label: 'guinea', flag: '🇬🇳' },
  { value: '+245', label: 'guinea_bissau', flag: '🇬🇼' },
  { value: '+240', label: 'equatorial_guinea', flag: '🇬🇶' },
  { value: '+509', label: 'haiti', flag: '🇭🇹' },
  { value: '+504', label: 'honduras', flag: '🇭🇳' },
  { value: '+852', label: 'hong_kong', flag: '🇭🇰' },
  { value: '+36', label: 'hungary', flag: '🇭🇺' },
  { value: '+91', label: 'india', flag: '🇮🇳' },
  { value: '+62', label: 'indonesia', flag: '🇮🇩' },
  { value: '+98', label: 'iran', flag: '🇮🇷' },
  { value: '+964', label: 'iraq', flag: '🇮🇶' },
  { value: '+353', label: 'ireland', flag: '🇮🇪' },
  { value: '+354', label: 'iceland', flag: '🇮🇸' },
  { value: '+972', label: 'israel', flag: '🇮🇱' },
  { value: '+39', label: 'italy', flag: '🇮🇹' },
  { value: '+81', label: 'japan', flag: '🇯🇵' },
  { value: '+962', label: 'jordan', flag: '🇯🇴' },
  { value: '+7', label: 'kazakhstan', flag: '🇰🇿' },
  { value: '+254', label: 'kenya', flag: '🇰🇪' },
  { value: '+965', label: 'kuwait', flag: '🇰🇼' },
  { value: '+371', label: 'latvia', flag: '🇱🇻' },
  { value: '+961', label: 'lebanon', flag: '🇱🇧' },
  { value: '+231', label: 'liberia', flag: '🇱🇷' },
  { value: '+218', label: 'libya', flag: '🇱🇾' },
  { value: '+370', label: 'lithuania', flag: '🇱🇹' },
  { value: '+352', label: 'luxembourg', flag: '🇱🇺' },
  { value: '+261', label: 'madagascar', flag: '🇲🇬' },
  { value: '+265', label: 'malawi', flag: '🇲🇼' },
  { value: '+223', label: 'mali', flag: '🇲🇱' },
  { value: '+356', label: 'malta', flag: '🇲🇹' },
  { value: '+212', label: 'morocco', flag: '🇲🇦' },
  { value: '+230', label: 'mauritius', flag: '🇲🇺' },
  { value: '+222', label: 'mauritania', flag: '🇲🇷' },
  { value: '+52', label: 'mexico', flag: '🇲🇽' },
  { value: '+373', label: 'moldova', flag: '🇲🇩' },
  { value: '+377', label: 'monaco', flag: '🇲🇨' },
  { value: '+976', label: 'mongolia', flag: '🇲🇳' },
  { value: '+382', label: 'montenegro', flag: '🇲🇪' },
  { value: '+258', label: 'mozambique', flag: '🇲🇿' },
  { value: '+264', label: 'namibia', flag: '🇳🇦' },
  { value: '+31', label: 'netherlands', flag: '🇳🇱' },
  { value: '+64', label: 'new_zealand', flag: '🇳🇿' },
  { value: '+505', label: 'nicaragua', flag: '🇳🇮' },
  { value: '+227', label: 'niger', flag: '🇳🇪' },
  { value: '+234', label: 'nigeria', flag: '🇳🇬' },
  { value: '+47', label: 'norway', flag: '🇳🇴' },
  { value: '+968', label: 'oman', flag: '🇴🇲' },
  { value: '+92', label: 'pakistan', flag: '🇵🇰' },
  { value: '+507', label: 'panama', flag: '🇵🇦' },
  { value: '+595', label: 'paraguay', flag: '🇵🇾' },
  { value: '+51', label: 'peru', flag: '🇵🇪' },
  { value: '+63', label: 'philippines', flag: '🇵🇭' },
  { value: '+48', label: 'poland', flag: '🇵🇱' },
  { value: '+351', label: 'portugal', flag: '🇵🇹' },
  { value: '+974', label: 'qatar', flag: '🇶🇦' },
  { value: '+40', label: 'romania', flag: '🇷🇴' },
  { value: '+7', label: 'russia', flag: '🇷🇺' },
  { value: '+250', label: 'rwanda', flag: '🇷🇼' },
  { value: '+966', label: 'saudi_arabia', flag: '🇸🇦' },
  { value: '+221', label: 'senegal', flag: '🇸🇳' },
  { value: '+381', label: 'serbia', flag: '🇷🇸' },
  { value: '+232', label: 'sierra_leone', flag: '🇸🇱' },
  { value: '+65', label: 'singapore', flag: '🇸🇬' },
  { value: '+421', label: 'slovakia', flag: '🇸🇰' },
  { value: '+386', label: 'slovenia', flag: '🇸🇮' },
  { value: '+252', label: 'somalia', flag: '🇸🇴' },
  { value: '+249', label: 'sudan', flag: '🇸🇩' },
  { value: '+211', label: 'south_sudan', flag: '🇸🇸' },
  { value: '+46', label: 'sweden', flag: '🇸🇪' },
  { value: '+41', label: 'switzerland', flag: '🇨🇭' },
  { value: '+963', label: 'syria', flag: '🇸🇾' },
  { value: '+255', label: 'tanzania', flag: '🇹🇿' },
  { value: '+235', label: 'chad', flag: '🇹🇩' },
  { value: '+66', label: 'thailand', flag: '🇹🇭' },
  { value: '+228', label: 'togo', flag: '🇹🇬' },
  { value: '+216', label: 'tunisia', flag: '🇹🇳' },
  { value: '+90', label: 'turkey', flag: '🇹🇷' },
  { value: '+380', label: 'ukraine', flag: '🇺🇦' },
  { value: '+44', label: 'united_kingdom', flag: '🇬🇧' },
  { value: '+598', label: 'uruguay', flag: '🇺🇾' },
  { value: '+58', label: 'venezuela', flag: '🇻🇪' },
  { value: '+84', label: 'vietnam', flag: '🇻🇳' },
  { value: '+263', label: 'zimbabwe', flag: '🇿🇼' },
  { value: '+260', label: 'zambia', flag: '🇿🇲' },
];